apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: node-red
spec:
  acme:
    email: matt.thorley@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: dns-api-token
      selector:
        dnsZones:
        - cyonomy.net # FIXME: replace with ${domain} once CNAME removed
