apiVersion: v1
kind: Service
metadata:
  name: vector-lb
  namespace: vector
spec:
  selector:
    app.kubernetes.io/name: vector
  type: LoadBalancer
  ports:
    - name: vsyslog-udp
      protocol: UDP
      port: 514
      targetPort: syslog-source-i
#    - name: rsyslog-tcp
#      port: 514
#      protocol: TCP
#      targetPort: rsyslog-tcp
