apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-mosquitto
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mqtt
data:
  mosquitto.conf:
  |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    listener 1883
    listener 9090
    protocol websockets
#    allow_anonymous false
#    password_file /mosquitto/data/users.txt
