apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mosquitto-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mosquitto_pwds: |
          {{ .nodered_mqtt_user }}:{{ .nodered_mqtt_password }}
          {{ .tasmota_mqtt_user }}:{{ .tasmota_mqtt_password }}
          {{ .tempcontroller_mqtt_user }}:{{ .tempcontroller_mqtt_password }}
          {{ .zig2mqtt_mqtt_user }}:{{ .zig2mqtt_mqtt_password }}
  dataFrom:
  - extract:
      key: secret/mqtt
