apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-mqtt
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mosquitto_pwds: |
          {{ .nodered-mqtt-user }}:{{ .nodered-mqtt-password }}
          {{ .tasmota-mqtt-user }}:{{ .tasmota-mqtt-password }}
          {{ .tempcontroller-mqtt-user }}:{{ .tempcontroller-mqtt-password }}
          {{ .zig2mqtt-mqtt-user }}:{{ .zig2mqtt-mqtt-password }}
  dataFrom:
  - extract:
      key: secret/mqtt
