apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqtt-mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mqtt
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-1.0.0
