kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-red-claim
  namespace: node-red-oidc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

