apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-local-egress-loki"
spec:
  endpointSelector:
    matchLabels:
      app: node-red
  egress:
  - toEndpoints:
    - matchLabels:
        "namespace": loki
        "name": loki
