apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-local-egress-adguard"
spec:
  endpointSelector:
    matchLabels:
      app: node-red
  egress:
  - toServices:
    - k8sService:
        serviceName: adguard-home-web
        namespace: adguard-home
