apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: node-red
spec:
  dnsNames:
    - nodered.internal.com
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
