apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: node-red
spec:
  vault:
    path: pki_int/sign/internal-dot-com
    server: "http://vault.vault:8200"
    #caBundle: <base64 encoded caBundle PEM file>
    auth:
      kubernetes:
        role: nodered-issuer-cert-role
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: nodered-token-brjkw # nodered service account
          key: token