apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  namespace: node-red
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      serviceAccountName: nodered
      containers:
      - name: node-red
        image: mthorley/node-red:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 1880
          name: node-red-ui
        securityContext:
          privileged: true
        volumeMounts:
        - name: node-red-data
          mountPath: /data
        env:
        - name: TZ
          value: Australia/Melbourne
        - name: MQTT_IP
          value: 192.168.3.14
        - name: NODE_RED_ENABLE_PROJECTS
          value: "true"
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-nodered
              key: mqtt-password
      volumes:
      - name: node-red-data
        persistentVolumeClaim:
          claimName: node-red-claim
