apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  namespace: node-red
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/role: 'nodered'
        vault.hashicorp.com/tls-skip-verify: 'true' # testing
        vault.hashicorp.com/agent-inject-secret-config: 'secret/nodered/MQTT_IP'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/nodered/MQTT_IP" -}}
            export MQTT_IP="{{ .Data.nodered.MQTT_IP }}"
          {{- end }}
    spec:
      containers:
      - name: node-red
        image: mthorley/node-red:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 1880
          name: node-red-ui
        securityContext:
          privileged: true
        volumeMounts:
        - name: node-red-data
          mountPath: /data
        env:
        - name: TZ
          value: Australia/Melbourne
#        - name: MQTT_IP
#          value: 192.168.3.14
      volumes:
      - name: node-red-data
        persistentVolumeClaim:
          claimName: node-red-claim
