apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodered
  labels:
    app: node-red
---
# to support vault token verifier
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: node-red
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: nodered
    namespace: node-red
