apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend-nodered
  namespace: node-red
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "nodered-secrets-role"
