apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-mongodb
  namespace: mongodb
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-mongodb
  dataFrom:
  - extract:
      key: secret/mongodb
