apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  loadBalancerIP: "${mongodb_ip}"
  ports:
    - name: db
      port: 27017
      protocol: TCP
  selector:
    app: mongodb
