apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-ext-egress-fglair"  # Fujitsu AC HA component
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  egress:
  - toFQDNs:
    - matchPattern: "user-field.aylanetworks.com"
    - matchPattern: "usfield-kube-ingress-lb-2134860999.us-east-1.elb.amazonaws.com"
