apiVersion: batch/v1
kind: CronJob
metadata:
  name: ha-backup
spec:
  schedule: "0 0 * * *" # midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ha-backup
              image: "arm64v8/alpine:3.17"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - cp -r /config/backups /target
              volumeMounts:
                - name: nfs-volume
                  mountPath: /target
          restartPolicy: OnFailure
          volumes:
            - name: nfs-volume
              nfs:
                server: "${qnap_ip}"
                path: /k8s/backup/ha
