apiVersion: v1
kind: Service
metadata:
  name: neuvector-lb-webui
  namespace: neuvector
spec:
  selector:
    app: neuvector-manager-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
  type: LoadBalancer
