apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: monitoring
spec:
  dnsNames:
    - "grafana.${domain}"
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
