apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: monitoring
spec:
  vault:
    path: "${pki_path}"
    server: "http://vault.vault:8200"
    #caBundle: <base64 encoded caBundle PEM file>
    auth:
      kubernetes:
        role: grafana-issuer-cert-role
        mountPath: /v1/auth/kubernetes
