apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: 9965
    relabelings:
    - action: keep
      regex: true
      sourceLabels:
      - __meta_kubernetes_service_annotation_prometheus_io_scrape
    - action: replace
      regex: (.+)(?::\d+);(\d+)
      replacement: $1:$2
      sourceLabels:
      - __address__
      - __meta_kubernetes_service_annotation_prometheus_io_port
      targetLabel: __address__
  jobLabel: kubernetes-endpoints
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: hubble
