apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: ${ACME_EMAIL}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: "${APP}-le-staging-account-key"
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: "${APP}-cloudflare-api-token-secret"
            key: dns-api-token
      selector:
        dnsZones:
        - "${domain}"
