# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - namespace.yaml
  - service-account.yaml
  - kagent-crds-stack.yaml
  - kagent-stack.yaml
  - mcp-fetch.yaml
  - gateway.yaml

components:
  - ../../../components/secrets-eso-vault
  - ../../../components/pki-certman-letsencrypt
