# values.yaml
config: |
  ffmpeg:
    hwaccel_args: preset-rpi-64-h264
  mqtt:
    host: "192.168.3.14"
    port: 1883
    user: test
    password: test
  cameras:
    # Define at least one camera
    front:
      ffmpeg:
        inputs:
          - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.1.71:554
            roles:
              - detect
              - rtmp
          - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.1.71:554
            roles:
              - record
      detect:
        width: 1280
        height: 720
service:
  type: LoadBalancer
  loadBalancerIP: "${mqtt_ip}"
