# values.yaml
config: |
  mqtt:
    host: "192.168.3.14"
    port: 1883
    user: test
    password: test
  cameras:
    # Define at least one camera
    front:
      ffmpeg:
        inputs:
          - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.71:554
            roles:
              - detect
              - rtmp
      detect:
        width: 1280
        height: 720

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.31
