# values.yaml
config: |
  mqtt:
    enabled: False
  cameras:
    front: # <------ Name the camera
      enabled: True
        ffmpeg:
          inputs:
          - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.2.71:554
              roles:
                - detect
        detect:
          enabled: False # <---- disable detection until you have a working camera feed

service:
  type: LoadBalancer
  loadBalancerIP: "${frigate_ip}"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - frigate
