# values.yaml
image:
  tag: "0.13.2"

config: |
  ffmpeg:
    hwaccel_args: preset-rpi-64-h264
  mqtt:
    enabled: False
  cameras:
    front:
      enabled: True
      ffmpeg:
        inputs:
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.2.71:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.2.71:554/h264Preview_01_main
          roles:
            - record
      detect:
        enabled: True
      rtmp: 
        enabled: False
  detectors:
    coral:
      type: edgetpu
      device: usb
  record:
    enabled: True
    retain:
      days: 3
      mode: motion
    events:
      retain:
        default: 30
        mode: motion

service:
  type: LoadBalancer
  loadBalancerIP: "${frigate_ip}"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - frigate

coral:
  enabled: True

persistence:
  media:
    enabled: true
    size: 10Gi
