# values.yaml
config: |
  ffmpeg:
    hwaccel_args: preset-rpi-64-h264
  mqtt:
    host: "mqtt-mosquitto.mqtt"
    port: 1883
    user: test
    password: test
  cameras:
    # Define at least one camera
    front:
      ffmpeg:
        inputs:
          - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.2.71:554
            roles:
              - detect
              - rtmp
          - path: rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@192.168.2.71:554
            roles:
              - record
      detect:
        width: 1280
        height: 720
service:
  type: LoadBalancer
  loadBalancerIP: "${frigate_ip}"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - frigate
