apiVersion: v1
kind: Service
metadata:
  name: pocket-id-postgres
  namespace: pocket-id
  labels:
    app: pocket-id-postgres
spec:
  type: ClusterIP
  selector:
    app: pocket-id-postgres
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
