apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentdvr
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - loadbalancer.yaml
  - deny-all-egress-netpol.yaml
  - allow-ext-egress-netpol.yaml
  - allow-local-egress-dns-netpol.yaml
#  - service.yaml
#  - ingress.yaml
#  - cert-issuer.yaml
#  - cert.yaml
