kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: agentdvr-claim
  namespace: agentdvr
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
