apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: torrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: deluge
          image: linuxserver/deluge
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "512Mi"
          env:
           - name: PUID
             value: "65534"
           - name: PGID
             value: "65534"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          ports:
            - containerPort: 8112
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: torrent-config-claim
        - name: downloads
          persistentVolumeClaim:
            claimName: torrent-download-claim
