apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge
  namespace: torrent
  labels:
    app: deluge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - name: deluge
          image: linuxserver/deluge
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "512Mi"
          env:
           - name: PUID
             value: "65534"
           - name: PGID
             value: "65534"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: nfs-volume
              mountPath: /nas
          ports:
            - name: torrent-ui
              containerPort: 8112         # Deluge Web UI
              protocol: TCP
            - name: torrent-daemon
            - containerPort: 58846        # Daemon port
              protocol: TCP
          # Set Deluge to use Gluetun's DNS to ensure all traffic is routed via VPN
          dnsPolicy: None
          dnsConfig:
            nameservers:
            - 127.0.0.1                   # Gluetun's DNS resolver inside the Pod
        - name: gluetun
          image: qmcgaw/gluetun
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "expressvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: secret-vpn
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-vpn
                  key: password
            - name: SERVER_COUNTRIES
              value: "Singapore"
            - name: TZ
              value: "${cluster_tz}"
            - name: FIREWALL_INPUT_PORTS
              value: "8112"                 # deluge UI
          securityContext:
              capabilities:
                add: ["NET_ADMIN"]
          volumeMounts:
            - name: vpn-config
              mountPath: /config
      volumes:
        - name: vpn-config
          persistentVolumeClaim:
            claimName: vpn-config-claim
        - name: config
          persistentVolumeClaim:
            claimName: torrent-config-claim
        - name: downloads
          persistentVolumeClaim:
            claimName: torrent-download-claim
        - name: nfs-volume
          nfs:
            server: "${qnap_ip}"
            path: "/k8s/torrents"
