apiVersion: v1
kind: Service
metadata:
  name: torrent-ui
  namespace: torrent
  labels:
    app: deluge
spec:
  type: LoadBalancer
  loadBalancerIP: "${torrent_ip}"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8112
  selector:
    app: deluge
