apiVersion: v1
kind: Service
metadata:
  name: torrent-internal
  namespace: torrent
spec:
  selector:
    app: deluge
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: torrent-ui
