apiVersion: v1
kind: Service
metadata:
  name: torrent-internal
  namespace: torrent
spec:
  selector:
    app: deluge
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: torrent-ui
      protocol: TCP
    - name: daemon 
      port: 58846
      targetPort: torrent-daemon         # Deluge Daemon
      protocol: TCP
