apiVersion: v1
kind: Secret
metadata:
  name: cf-tunnel-creds
  namespace: cf
  annotations:
    kubernetes.io/service-account.name: cf-tunnel
  labels:
    app: cloudflared
type: kubernetes.io/service-account-token
