apiVersion: v1
kind: ConfigMap
data:
  config: |
    peers:
    - peer-address: 192.168.2.1
      peer-asn: 64512
      my-asn: 64512
    address-pools:
    - name: production-pool
      protocol: bgp
      addresses:
      - 192.168.2.10-192.168.2.40
      avoid-buggy-ips: true
metadata:
  name: config
  namespace: metallb-system
