apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: production-cluster
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 65023
  peerAddress: 192.168.1.1
  peerPort: 179
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.10-192.168.2.40
  autoAssign: true
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: services
  namespace: metallb-system
spec:
  ipAddressPools:
  - production-pool
