apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: production-pool
  namespace: metallb-system
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 192.168.2.1
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.10-192.168.2.40
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: production-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - production-pool
