apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: adguard-home
spec:
  dnsNames:
    - "adguard.${domain}"
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
