apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_tz: "Australia/Melbourne"
      # FIXME: Ingress this up 
      rsyslog_ip: 192.168.2.12
      pi_temp_agent_ip: 192.168.2.13
      mqtt_ip: 192.168.2.11
      adguard_web_ip: 192.168.2.16
      adguard_dns_ip: 192.168.2.17
      jupyter_ip: 192.168.2.18
      homeassistant_ip: 192.168.2.19
      crypto_agent_ip: 192.168.2.22
      unifi_ip: 192.168.2.23
      nodered_syslog_ip: 192.168.2.26   # syslog.cluster
      nodered_web_ip: 192.168.2.14
      zigbee2mqtt_ip: 192.168.2.30
      # external
      qnap_ip: 192.168.1.147
