# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ha-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 30m0s
  path: ./apps/production/ha-dev
  prune: true
  postBuild:
    substitute:
      APP: "homeassistant"
      BACKUP_SOURCE_CLAIM: "home-assistant-config"
      BACKUP_SCHEDULE: "0 0 * * *"
      cluster_tz: "Australia/Melbourne"
      homeassistant_ip: 192.168.2.19
      qnap_ip: 192.168.1.147
      cluster_id: cluster0
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: homeassistant
  wait: false
