apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 20m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production
  prune: true
  validation: client
  postBuild:
    substitute:
      nfs_server_ip: 192.168.2.113
      # FIXME: Ingress this up
      hubble_ui_ip: 192.168.2.31
      influxdb_ip: 192.168.2.20
      mongodb_ip: 192.168.2.21
      vault_ip: 192.168.2.28
      nginx_ip: 192.168.2.29
      # external
      qnap_ip: 192.168.1.147
      pki_path: pki_int/sign/internal-dot-com
      domain: cluster0.net
      cluster_id: 0
