apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-external-egress"
spec:
  endpointSelector:
    matchLabels:
      app: crypto-agent
  egress:
    - toFQDNs:
      - matchName: "coinspot.com.au"
      - matchName: "telegram.org"
