apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: crypto-agent
  namespace: crypto-automate
  labels:
    app: crypto-agent
spec:
  selector:
    matchLabels:
      app: crypto-agent
  template:
    metadata:
      labels:
        app: crypto-agent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: crypto-agent
        image: mthorley/crypto-automate:latest
        env:
        - name: COINSPOT_SECRET_RO
          valueFrom:
            secretKeyRef:
              name: secret-cryptoautomation
              key: coinspot-secret-ro
        - name: COINSPOT_KEY_RO
          valueFrom:
            secretKeyRef:
              name: secret-cryptoautomation
              key: coinspot-key-ro
        - name: TELEGRAM_BOT_NAME
          valueFrom:
            secretKeyRef:
              name: secret-cryptoautomation
              key: telegram-bot-name
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-cryptoautomation
              key: telegram-bot-token
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: secret-cryptoautomation
              key: telegram-chat-id
        ports:
        - containerPort: 8080
