apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-cryptoautomation
  namespace: crypto-automate
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-cryptoautomation
  dataFrom:
  - extract:
      key: secret/cryptoautomation
