apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: authentik
spec:
  dnsNames:
    - "auth.${domain}"
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
