apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: authentik
spec:
  vault:
    path: pki_int/sign/internal-dot-com
    server: "http://vault.vault:8200"
    #caBundle: <base64 encoded caBundle PEM file>
    auth:
      kubernetes:
        role: auth-issuer-cert-role
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: authentik-token-6zwx8
          key: token