apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-com
  namespace: authentik
spec:
  dnsNames:
    - "auth.${domain}"
  secretName: domain-tls
  issuerRef:
    name: vault-issuer
