apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - authentik-stack.yaml
  - cert-issuer.yaml
  - cert.yaml
#  - ingress-outpost.yaml
  - ingress-outpost-nodered.yaml
