# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - service-account.yaml
  - service-account-token-secret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
  - gateway.yaml
#  - ingress-outpost.yaml
#  - ingress-outpost-nodered.yaml

components:
  - ../../../components/pki-certman-letsencrypt

patchesStrategicMerge:
  - cert-hostname-patch.yaml
