apiVersion: v1
kind: Service
metadata:
  name: authentik-public
  namespace: authentik
spec:
  selector:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/component: "server"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
