apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock-minecraft-public
  labels:
    app: minecraft-bedrock-minecraft
    chart: "minecraft-3.4.2"
    release: "minecraft-bedrock"
    heritage: "Helm"
  annotations:
    {}
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 19132
    targetPort: minecraft
    protocol: TCP
  selector:
    app: minecraft-bedrock-minecraft