kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
