---
apiVersion: v1
kind: Service
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: hubble-ui
  type: LoadBalancer
  loadBalancerIP: "${hubble_ui_ip}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
