apiVersion: v1
kind: Service
metadata:
  name: rsyslog-lb
spec:
  selector:
    app: rsyslog
  type: LoadBalancer
  ports:
    - name: rsyslog-udp
      protocol: UDP
      port: 514
      targetPort: rsyslog-udp
#    - name: rsyslog-tcp
#      port: 514
#      protocol: TCP
#      targetPort: rsyslog-tcp
