apiVersion: v1
kind: Service
metadata:
  name: pi-temp-public
  namespace: pi-temp
spec:
  selector:
    app: pi-temp-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 192.168.3.13

