apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-external-egress"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: unifi
  egress:
  - toCIDR:
    - 192.168.0.0/16
  - toFQDNs:
    - matchName: "ips1.unifi-ai.com" # IDS/IPS rule updates
    - matchName: "ips.svc.ui.com"
    - matchName: "config.ubnt.com"
    - matchName: "static.ubnt.com"
    - matchName: "fw-update.ubnt.com"
#    - matchName: "trace.svc.ui.com" # Block analytics from ui
