apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: unifi-controller
spec:
  dnsNames:
    - unifi.internal.com
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
