apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: unifi-controller
spec:
  vault:
    path: "${pki_path}"
    server: "http://vault.vault:8200"
    #caBundle: <base64 encoded caBundle PEM file>
    auth:
      kubernetes:
        role: unifi-issuer-cert-role
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: default-token-w6jhs
          key: token