
image:
  repository: jacobalberty/unifi
#  tag: v6.5.55
  tag: v7.1.66
#service:
#  main:
#    type: LoadBalancer
#    loadBalancerIP: 192.168.3.23
#    externalTrafficPolicy: Local
persistence:
  data:
    enabled: true
    size: 20Gi
    storageClass: managed-nfs-storage
    accessMode: ReadWriteOnce
env:
  RUNAS_UID0: "true"
  TZ: "${cluster_tz}"
resources:
    requests:
      memory: 500Mi
      cpu: 15m
    limits:
      memory: 750Mi
