
image:
  repository: jacobalberty/unifi
#  tag: v7.1.66
#  tag: v7.2.95
#  tag: v7.3.83
#  tag: v7.4.156
  tag: v8.0.28

# Migration to new repo and image version
#  repository: nexusforge/unifi-docker
#  tag: v8.0.24
#    > v7.5.187   # target for psk's

#service:
#  main:
#    type: LoadBalancer
#    loadBalancerIP: ${unifi_ip}
#    externalTrafficPolicy: Local
persistence:
  data:
    enabled: true
    size: 20Gi
    storageClass: managed-nfs-storage
    accessMode: ReadWriteOnce
env:
  RUNAS_UID0: "true"
  TZ: "${cluster_tz}"
resources:
    requests:
      memory: 500Mi
      cpu: 15m
    limits:
      memory: 750Mi
