apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  timeout: 2m0s
  interval: 15m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_tz: "Australia/Melbourne"
      # FIXME: Ingress this up 
      adguard_web_ip: 192.168.3.16
      adguard_dns_ip: 192.168.3.17
      crypto_agent_ip: 192.168.3.22
      homeassistant_ip: 192.168.3.19
      jupyter_ip: 192.168.3.18
      mqtt_ip: 192.168.3.14
      pi_temp_agent_ip: 192.168.3.13
      unifi_ip: 192.168.3.23
      nodered_syslog_ip: 192.168.3.26
      nodered_web_ip: 192.168.3.27
      qnap_ip: 192.168.1.147
