apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_tz: "Australia/Melbourne"
      # FIXME: Ingress this up 
      pi_temp_agent_ip: 192.168.3.13
      mqtt_ip: 192.168.3.14
      adguard_web_ip: 192.168.3.16
      adguard_dns_ip: 192.168.3.17
      jupyter_ip: 192.168.3.18
      homeassistant_ip: 192.168.3.19
      crypto_agent_ip: 192.168.3.22
      unifi_ip: 192.168.3.23
      freeradius_acc_ip: 192.168.3.24
      freeradius_auth_ip: 192.168.3.25
      nodered_syslog_ip: 192.168.3.26
      nodered_web_ip: 192.168.3.27
      zigbee2mqtt_ip: 192.168.3.30
      agentdvr_ip: 192.168.3.31
      # external
      qnap_ip: 192.168.1.147
