apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging
  prune: true
  validation: client
  postBuild:
    substitute:
      # FIXME: Ingress this up 
      grafana_ip: 192.168.3.10
      qnap_ip: 192.168.1.147
      mongodb_ip: 192.168.3.21
      influxdb_ip: 192.168.3.20
      hubble_ui_ip: 192.168.3.11
