# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-red
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: gateway-api-crds
    - name: nginx-gateway
  interval: 30m0s
  path: ./apps/common/node-red
  prune: true
  postBuild:
    substitute:
      APP: "nodered"
      ACME_EMAIL: "matt.thorley@gmail.com"
      cluster_tz: "Australia/Melbourne"
      mqtt_ip: 192.168.3.14
      nodered_web_ip: 192.168.3.27
      nodered_syslog_ip: 192.168.3.26
      domain: cluster1.cyonomy.net
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: node-red
  wait: false
