---
# Source: vault-secrets-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
---
# Source: vault-secrets-operator/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole
metadata:
  name: vault-secrets-operator-default
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - authorization.k8s.io
    resources:
    - subjectaccessreviews
    verbs:
    - create
---
# Source: vault-secrets-operator/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - coordination.k8s.io
  - ""
  resources:
  - configmaps
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricoberger.de
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricoberger.de
  resources:
  - vaultsecrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricoberger.de
  resources:
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
---
# Source: vault-secrets-operator/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-operator-default
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-secrets-operator-default
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: vault-secrets-operator
    namespace: default
---
# Source: vault-secrets-operator/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-secrets-operator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: vault-secrets-operator
    namespace: default
---
# Source: vault-secrets-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/instance: vault-secrets-operator
---
# Source: vault-secrets-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    helm.sh/chart: vault-secrets-operator-1.15.1
    app.kubernetes.io/instance: vault-secrets-operator
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-secrets-operator
      app.kubernetes.io/instance: vault-secrets-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-secrets-operator
        helm.sh/chart: vault-secrets-operator-1.15.1
        app.kubernetes.io/instance: vault-secrets-operator
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: vault-secrets-operator
      securityContext:
        {}
      containers:
        - name: vault-secrets-operator
          securityContext:
            {}
          image: "ricoberger/vault-secrets-operator:1.15.1"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - -leader-elect
          env:
            - name: VAULT_ADDRESS
              value: "http://vault:8200"
            - name: WATCH_NAMESPACE
              value: ""
            - name: VAULT_AUTH_METHOD
              value: "kubernetes"
            - name: VAULT_TOKEN_PATH
              value: ""
            - name: VAULT_KUBERNETES_PATH
              value: "auth/kubernetes"
            - name: VAULT_KUBERNETES_ROLE
              value: "vault-secrets-operator"
            - name: VAULT_APP_ROLE_PATH
              value: "auth/approle"
            - name: VAULT_RECONCILIATION_TIME
              value: "0"
            - name: VAULT_AZURE_PATH
              value: "auth/azure"
            - name: VAULT_AZURE_ROLE
              value: "default"
            - name: VAULT_AZURE_ISSCALESET
              value: 
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {}
---
# Source: vault-secrets-operator/templates/tests/test-connection.yaml
#apiVersion: v1
#kind: Pod
#metadata:
#  name: "vault-secrets-operator-test-connection"
#  labels:
#    app.kubernetes.io/name: vault-secrets-operator
#    helm.sh/chart: vault-secrets-operator-1.15.1
#    app.kubernetes.io/instance: vault-secrets-operator
#    app.kubernetes.io/managed-by: Helm
    
#  annotations:
#    "helm.sh/hook": test-success
    
#spec:
#  containers:
#    - name: wget
#      image: busybox:latest
#      command: ['wget']
#      args:  ['vault-secrets-operator:8081/healthz']
#  restartPolicy: Never
