apiVersion: v1
kind: Service
metadata:
  name: vault-external
  namespace: vault
spec:
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  type: LoadBalancer
  ports:
    - name: http
      port: 8200
      targetPort: 8200
