server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: managed-nfs-storage
    accessMode: ReadWriteOnce

ui:
  enabled: true
#  serviceType: LoadBalancer

injector:
  enabled: false