apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/pi-temp-agent
#  - ../common/rsyslog
  - ../common/mqtt
  - mqtt-vault-secret.yaml
  - mqtt-vault-secret-store.yaml
#  - ../common/node-red
#  - ../common/adguard
#  - ../common/jupyternb
#  - ../common/crypto-automation
#  - ../common/unifi-controller
#  - ../common/homeassistant
#  - ../common/zigbee2mqtt
