apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/pi-temp-agent
#  - ../common/rsyslog
  - ../common/mqtt
  - mqtt-vault-secret.yaml
  - mqtt-vault-secret-store.yaml
  - ../common/node-red
  - nodered-vault-secret-store.yaml
  - nodered-vault-secret.yaml
  - nodered-vaultissuer-role.yaml
  - ../common/adguard
  - adguard-vaultissuer-role.yaml
#  - ../common/jupyternb
#  - ../common/crypto-automation
#  - ../common/unifi-controller
#  - ../common/homeassistant
#  - ../common/zigbee2mqtt
  - ../common/frigate
#  - frigate-vault-secret.yaml
#  - frigate-vault-secret-store.yaml
patchesStrategicMerge:
  - cert-issuer-nodered.yaml
  - cert-issuer-adguard.yaml
