apiVersion: v1
kind: Secret
metadata:
  name: vault-k8s-auth-secret
  namespace: mqtt
  annotations:
    kubernetes.io/service-account.name: mqtt-mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mqtt
type: kubernetes.io/service-account-token
