apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-zig2mqtt
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-zig2mqtt
  dataFrom:
  - extract:
      key: secret/zig2mqtt
