apiVersion: v1
kind: Service
metadata:
  name: zm-lb
spec:
  selector:
    app.kubernetes.io/name: zigbee2mqtt
  type: LoadBalancer
  loadBalancerIP: "${zigbee2mqtt_ip}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
