---
# Source: grafana-mcp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcp
  namespace: grafana-mcp
  labels:
    helm.sh/chart: grafana-mcp-0.1.1
    app.kubernetes.io/name: grafana-mcp
    app.kubernetes.io/instance: grafana-mcp
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: mcp-server
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: mcp-http
      protocol: TCP
      name: mcp-http
  selector:
    app.kubernetes.io/name: grafana-mcp
    app.kubernetes.io/instance: grafana-mcp
    app.kubernetes.io/component: mcp-server
---
# Source: grafana-mcp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp
  namespace: grafana-mcp
  labels:
    helm.sh/chart: grafana-mcp-0.1.1
    app.kubernetes.io/name: grafana-mcp
    app.kubernetes.io/instance: grafana-mcp
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: mcp-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-mcp
      app.kubernetes.io/instance: grafana-mcp
      app.kubernetes.io/component: mcp-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-mcp
        app.kubernetes.io/instance: grafana-mcp
        app.kubernetes.io/component: mcp-server
      annotations:
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: mcp-grafana
          image: "docker.io/mcp/grafana:latest"
          imagePullPolicy: Always
          args: ["-t", "streamable-http"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: mcp-http
              containerPort: 8000
              protocol: TCP
          env:
            - name: GRAFANA_URL
              value: http://grafana.monitoring.svc:3000
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-grafana-mcp
                  key: apikey
