apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: adguard-home
spec:
  vault:
    auth:
      kubernetes:
        secretRef:
          name: default-token-hcmrw
          key: token
