apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: node-red
spec:
  vault:
    auth:
      kubernetes:
        secretRef:
          name: nodered-token-brjkw # nodered service account
          key: token
