apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: mqtt
spec:
  provider:
    vault:
      auth:
        kubernetes:
          serviceAccountRef:
            name: "mqtt-mosquitto"
