apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-nodered-cf-api-token
  namespace: node-red
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cloudflare-api-token-secret
  dataFrom:
  - extract:
      key: secret/nodered-cf-api-token
