apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: jupyter
spec:
  dnsNames:
    - internal.com
    - jupyter.internal.com
  secretName: vault-cert-tls
  issuerRef:
    name: vault-issuer