apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: jupyter
spec:
  commonName: interal.com
  dnsNames:
    - internal.com
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
