kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyternb-claim
  namespace: jupyter
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
