apiVersion: v1
kind: Service
metadata:
  name: jupyternb
  namespace: jupyter
spec:
  selector:
    app: jupyternb
  type: LoadBalancer
  loadBalancerIP: "${jupyter_ip}"
  ports:
    - name: jupyternb-ui
      port: 80
      protocol: TCP
      targetPort: jupyternb-ui
