---
# Source: nginx-gateway-fabric/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngf-nginx-gateway-fabric
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
automountServiceAccountToken: false
---
# Source: nginx-gateway-fabric/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngf-nginx-gateway-fabric
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - update
  - delete
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - create
  - update
  - delete
  - list
  - get
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - update
  - delete
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  - grpcroutes
  - backendtlspolicies
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  - gateways/status
  - gatewayclasses/status
  - grpcroutes/status
  - backendtlspolicies/status
  verbs:
  - update
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxproxies
  - clientsettingspolicies
  - observabilitypolicies
  - upstreamsettingspolicies
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways/status
  - clientsettingspolicies/status
  - observabilitypolicies/status
  - upstreamsettingspolicies/status
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
---
# Source: nginx-gateway-fabric/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngf-nginx-gateway-fabric
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngf-nginx-gateway-fabric
subjects:
- kind: ServiceAccount
  name: ngf-nginx-gateway-fabric
  namespace: nginx-gateway
---
# Source: nginx-gateway-fabric/templates/service.yaml
# This is the control plane Service for internal communication with the data plane.
# To get an NGINX LoadBalancer Service, create a Gateway resource once NGINX Gateway Fabric is installed.
apiVersion: v1
kind: Service
metadata:
  name: ngf-nginx-gateway-fabric
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
  ports:
  - name: agent-grpc
    port: 443
    protocol: TCP
    targetPort: 8443
---
# Source: nginx-gateway-fabric/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngf-nginx-gateway-fabric
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
      app.kubernetes.io/instance: ngf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-gateway-fabric
        app.kubernetes.io/instance: ngf
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - controller
        - --gateway-ctlr-name=gateway.nginx.org/nginx-gateway-controller
        - --gatewayclass=nginx
        - --config=ngf-config
        - --service=ngf-nginx-gateway-fabric
        - --agent-tls-secret=agent-tls
        - --metrics-port=9113
        - --health-port=8081
        - --leader-election-lock-name=ngf-nginx-gateway-fabric-leader-election
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
        - name: IMAGE_NAME
          value: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
        image: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
        imagePullPolicy: IfNotPresent
        name: nginx-gateway
        ports:
        - name: agent-grpc
          containerPort: 8443
        - name: metrics
          containerPort: 9113
        - name: health
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 3
          periodSeconds: 1
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-agent-tls
          mountPath: /var/run/secrets/ngf
      terminationGracePeriodSeconds: 30
      serviceAccountName: ngf-nginx-gateway-fabric
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      volumes:
      - name: nginx-agent-tls
        secret:
          secretName: server-tls
---
# Source: nginx-gateway-fabric/templates/gatewayclass.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  controllerName: gateway.nginx.org/nginx-gateway-controller
  parametersRef:
    group: gateway.nginx.org
    kind: NginxProxy
    name: ngf-proxy-config
    namespace: nginx-gateway
---
# Source: nginx-gateway-fabric/templates/nginxgateway.yaml
apiVersion: gateway.nginx.org/v1alpha1
kind: NginxGateway
metadata:
  name: ngf-config
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  logging:
    level: info
---
# Source: nginx-gateway-fabric/templates/nginxproxy.yaml
apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: ngf-proxy-config
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  kubernetes:
    deployment:
      replicas: 1
      container:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/nginx/nginx-gateway-fabric/nginx
          tag: 2.3.0
    service:
      externalTrafficPolicy: Local
      type: LoadBalancer
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngf-nginx-gateway-fabric-cert-generator
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
automountServiceAccountToken: false
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ngf-nginx-gateway-fabric-cert-generator
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ngf-nginx-gateway-fabric-cert-generator
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ngf-nginx-gateway-fabric-cert-generator
subjects:
- kind: ServiceAccount
  name: ngf-nginx-gateway-fabric-cert-generator
  namespace: nginx-gateway
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: ngf-nginx-gateway-fabric-cert-generator
  namespace: nginx-gateway
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gateway-fabric
    app.kubernetes.io/instance: ngf
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
spec:
  template:
    metadata:
      annotations:
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - generate-certs
        - --service=ngf-nginx-gateway-fabric
        - --cluster-domain=cluster.local
        - --server-tls-secret=server-tls
        - --agent-tls-secret=agent-tls
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
        imagePullPolicy: IfNotPresent
        name: cert-generator
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
      restartPolicy: Never
      serviceAccountName: ngf-nginx-gateway-fabric-cert-generator
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
  ttlSecondsAfterFinished: 30
