apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 5m
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
