apiVersion: v1
kind: ConfigMap
metadata:
  name: apparmor-profiles
  namespace: apparmor
data:
  k8s-apparmor-audit-writes: |-
    #include <tunables/global>
    profile k8s-apparmor-audit-writes flags=(attach_disconnected) {
      #include <abstractions/base>

      # Allow all rules
      capability,
      network,
      network raw,
      network inet stream,
      network netlink raw,
      mount,
      remount,
      umount,
      pivot_root,
      ptrace,
      signal,
      dbus,
      unix,
      file,

      # Audit all file access
      audit /** mklrw,

    }
