---
# Source: pihole/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pihole-password
  labels:
    app: pihole
    chart: pihole-2.0.1
    heritage: Helm
    release: pihole
type: Opaque
data:
  password: "YWRtaW4="
