apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: pihole
  namespace: pi-hole
  labels:
    app: pihole
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"
