apiVersion: v1
kind: Service
metadata:
  name: pihole-dhcp
  namespace: pi-hole
  labels:
    app: pihole
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 67
      targetPort: client-udp
      protocol: UDP
      name: client-udp
  selector:
    app: pihole
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: pihole-dns-tcp
#  namespace: pi-hole
#  labels:
#    app: pihole
#spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
#  ports:
#    - port: 53
#      targetPort: dns
#      protocol: TCP
#      name: dns
#  selector:
#    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-udp
  namespace: pi-hole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pi-hole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: pihole
