apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: authentik
spec:
  vault:
    auth:
      kubernetes:
        secretRef:
          name: authentik-token-hf7nd
          key: token
