apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:12.3.1
        volumeMounts:
        # dashboards shipped with kube-prometheus-stack (staging only until
        # the stack is promoted)
        - mountPath: /grafana-dashboard-definitions/0/app-health
          name: grafana-dashboard-app-health
          readOnly: false
      volumes:
      - name: grafana-dashboard-app-health
        configMap:
          name: grafana-dashboard-app-health
