apiVersion: v1
kind: ConfigMap
data:
  config: |
    peers:
    - peer-address: 192.168.2.1
      peer-asn: 64512
      my-asn: 64511
    address-pools:
    - name: staging
      protocol: bgp
      addresses:
      - 192.168.3.10-192.168.3.40
      avoid-buggy-ips: true
metadata:
  name: config
  namespace: metallb-system
