apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius
  namespace: freeradius
  labels:
    app: freeradius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeradius
  template:
    metadata:
      labels:
        app: freeradius
    spec:
      serviceAccountName: freeradius
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: freeradius
        image: mthorley/freeradius:08e8faf9bba61a7c374d635da9fed92b4fca4f36
        imagePullPolicy: Always
        ports:
        - containerPort: 1812
          name: freeradius-auth
        - containerPort: 1813
          name: freeradius-acc
#        volumeMounts:
#        - name: radius-conf
#          mountPath: /etc/freeradius/3.0/radiusd.conf
#          subPath: radiusd.conf
        env:
        - name: AUTH_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-freeradius
              key: auth-shared-secret
        - name: APS_CIDR
          value: 192.168.1.1/24
 #     volumes:
 #       - name: radius-conf
 #         configMap:
 #           name: radius-config
