apiVersion: v1
kind: Service
metadata:
  name: freeradius-udp
  namespace: freeradius
spec:
  selector:
    app: freeradius
  type: LoadBalancer
#  loadBalancerIP: "${freeradius_ip}"
  ports:
    - name: freeradius-udp
      port: 1812
      protocol: UDP
      targetPort: 1812
