apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-com
  namespace: node-red-dev
spec:
  dnsNames:
    - nodereddev.internal.com
  secretName: internal-com-tls
  issuerRef:
    name: vault-issuer
