apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-nodered
  namespace: node-red-dev
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: secret-nodered
  dataFrom:
  - extract:
      key: secret/nodered
