apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-issuer
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['vault-issuer']
    verbs: ['create']
